servers:
  - http:
      port: 8080
      responses:
        /test:
          get:
            static:
              status: 200
              body: all good
              showheaders: true
          post:
            seq:
              - status: 500
                body: oops that did not work
              - status: 500
                body: try again buddy
              - status: 200
                body: whew now it worked
        /slow:
          get:
            seq:
              - status: 200
                body: this is a slow response
                delay: 500ms
              - status: 200
                body: this is even slower
                delay: 1s
        /loop:
          get:
            loop:
              - status: 200
                body: one
              - status: 200
                body: two
              - status: 200
                body: three
        /big:
          get:
            static:
              status: 200
              bigbody:
                size: 10M
                type: lorem
  - tcp:
      port: 8081
      responses:
        read:
          bufsize: 1M
        write:
          bufsize: 1M
          type: lorem
          delay: 500ms
  - websocket:
      port: 8082
      responses:
        /ws:
          read:
            bufsize: 1M
            delay: 1s
          write:
            bufsize: 1M
            type: binary
            delay: 1s
        /ws2:
          read:
            bufsize: 1M
          write:
            bufsize: 100B
            type: lorem
            delay: 1s
